limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

server {
    listen 80;

    resolver 127.0.0.11 valid=5s;

    location ~ ^/server/(.*)$ {
        limit_req zone=mylimit burst=20 nodelay;

        # Captures everything after /server/ and appends it to $backend
        set $path $1;
        set $backend "http://server:8000/$path";
        
        proxy_pass $backend;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        set $frontend "http://client:3000";
        proxy_pass $frontend;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}